"""remove phone number

Revision ID: e9a235143aed
Revises: 8f182eb62dd0
Create Date: 2022-01-11 18:14:51.829993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9a235143aed'
down_revision = '8f182eb62dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    # ### end Alembic commands ###
